DROP TABLE FLOWERSHOP;

DROP TABLE FLOWER_SALES;

CREATE TABLE FLOWERSHOP(
FLOWER_ID INTEGER,
FLOWER_NAME VARCHAR2(20) CONSTRAINT NN_FLOWER_NAME NOT NULL ,
PRICE_PER_KG INTEGER,
CONSTRAINT PK_FLOWER_ID PRIMARY KEY (FLOWER_ID));


CREATE TABLE FLOWER_SALES(FLOWER_ID INTEGER,
STOCK_AVAILABLE INTEGER,
QUANTITY_SOLD INTEGER,
CONSTRAINT FK_FLOWER_ID FOREIGN KEY(FLOWER_ID) REFERENCES FLOWERSHOP(FLOWER_ID));


CREATE TABLE STUDENT(STUD_ID INTEGER, 
STUDENT_NAME VARCHAR2(20) CONSTRAINT NN_STUDENT_NAME NOT NULL,
MARK1 INTEGER, MARK2 INTEGER, MARK3 INTEGER,
TOTAL_MARKS INTEGER,
AVG);

