DROP TABLE REGIONS;
ALTER TABLE REGIONS DROP PRIMARY KEY CASCADE;

DROP TABLE COUNTRIES;
ALTER TABLE COUNRIES DROP PRIMARY KEY CASCADE;


DROP TABLE LOCATIONS;
ALTER TABLE LOCATIONS DROP PRIMARY KEY CASCADE;


DROP TABLE JOBS_HISTORY;
ALTER TABLE JOBS_HISTORY DROP PRIMARY KEY CASCADE;

DROP TABLE JOBS;
ALTER TABLE JOBS DROP PRIMARY KEY CASCADE;

ALTER TABLE DEPT DROP PRIMARY KEY CASCADE;
DROP TABLE DEPT;
--DROP TABLE DEPT CASCADE CONSTRAINTS;


DROP TABLE EMP;
ALTER TABLE EMP DROP PRIMARY KEY CASCADE;
--DROP TABLE EMP CASCADE CONSTRAINTS;



DROP TABLE LOCATIONS;
ALTER TABLE LOCATIONS DROP PRIMARY KEY CASCADE;


CREATE TABLE REGIONS
(
  REG_ID    NUMBER(2) CONSTRAINT NN_REG_ID NOT NULL,
  REG_NAME  VARCHAR2(25 BYTE),
  CONSTRAINT PK_REG_ID PRIMARY KEY(REG_ID)
);

CREATE TABLE COUNTRIES
(
  COUNTRY_ID    CHAR(2 BYTE) CONSTRAINT COUNTRY_ID_NN NOT NULL,
  COUNTRY_NAME  VARCHAR2(40 BYTE),
  REG_ID     NUMBER(2),
  CONSTRAINT PK_COUNTRY_ID PRIMARY KEY(COUNTRY_ID),
  CONSTRAINT FK_REG_ID FOREIGN KEY(REG_ID) REFERENCES REGIONS(REG_ID)
);

CREATE TABLE LOCATIONS
(
  LOCATION_ID     NUMBER(4),
  STREET_ADDRESS  VARCHAR2(40 BYTE),
  POSTAL_CODE     VARCHAR2(12 BYTE),
  CITY            VARCHAR2(30 BYTE) CONSTRAINT NN_LOC_CITY NOT NULL,
  STATE_PROVINCE  VARCHAR2(25 BYTE),
  COUNTRY_ID      CHAR(2 BYTE),
  CONSTRAINT PK_LOCATION_ID PRIMARY KEY(LOCATION_ID),
  CONSTRAINT FK_COUNTRY_ID FOREIGN KEY(COUNTRY_ID) REFERENCES COUNTRIES(COUNTRY_ID)
);


CREATE TABLE DEPT
(
  DEPT_ID    NUMBER(4),
  DEPT_NAME  VARCHAR2(30 BYTE) CONSTRAINT NN_DEPT_NAME NOT NULL,
  MANAGER_ID       NUMBER(6),
  LOCATION_ID      NUMBER(4),
  CONSTRAINT PK_DEPT_ID PRIMARY KEY(DEPT_ID),
  CONSTRAINT FK_DEPT_LOC_ID FOREIGN KEY(LOCATION_ID) REFERENCES LOCATIONS(LOCATION_ID),
  CONSTRAINT FK_DEPT_MGR_ID FOREIGN KEY(MANAGER_ID) REFERENCES EMP(EMP_ID)
);

CREATE TABLE JOBS
(
  JOB_ID      VARCHAR2(10 BYTE),
  JOB_TITLE   VARCHAR2(35 BYTE) CONSTRAINT NN_JOB_TITLE NOT NULL,
  MIN_SALARY  NUMBER(6),
  MAX_SALARY  NUMBER(6),
  CONSTRAINT PK_JOB_ID PRIMARY KEY(JOB_ID)
);


CREATE TABLE EMP(
  EMP_ID     NUMBER(6),
  F_NAME      VARCHAR2(20 BYTE),
  L_NAME       VARCHAR2(25 BYTE) CONSTRAINT NN_EMP_LAST_NAME NOT NULL,
  EMAIL           VARCHAR2(25 BYTE) CONSTRAINT NN_EMP_EMAIL NOT NULL,
  PHONE_NUMBER    VARCHAR2(20 BYTE),
  HIRE_DATE       DATE CONSTRAINT NN_EMP_HIRE_DATE NOT NULL,
  JOB_ID          VARCHAR2(10 BYTE) CONSTRAINT NN_EMP_JOB NOT NULL,
  SALARY          NUMBER(8,2),
  COMMISSION_PCT  NUMBER(2,2),
  MANAGER_ID      NUMBER(6),
  DEPT_ID   NUMBER(4),
  CONSTRAINT PK_EMP_ID PRIMARY KEY(EMP_ID),
  CONSTRAINT CHK_SALARY CHECK (SALARY>0),
  CONSTRAINT UNI_EMAIL UNIQUE (EMAIL),
  CONSTRAINT FK_EMP_MANAGER FOREIGN KEY(MANAGER_ID) REFERENCES EMP(EMP_ID),
  CONSTRAINT FK_JOB_ID FOREIGN KEY (JOB_ID) REFERENCES JOBS(JOB_ID),
  CONSTRAINT FK_DEPT_ID FOREIGN KEY(DEPT_ID) REFERENCES DEPT(DEPT_ID)
);
