DECLARE 
  CURSOR CUR_EMP_IN_DEPT
  IS 
  SELECT EMP_ID, SALARY, HIRE_DATE FROM EMP WHERE DEPT_ID = 20;
  V_EMP_ID EMP.EMP_ID%TYPE;
  V_SALARY EMP.SALARY%TYPE;
  V_HIRE_DATE EMP.HIRE_DATE%TYPE;
BEGIN
  OPEN CUR_EMP_IN_DEPT;
  LOOP
   FETCH CUR_EMP_IN_DEPT INTO V_EMP_ID, V_SALARY, V_HIRE_DATE;
   EXIT
 WHEN CUR_EMP_IN_DEPT%NOTFOUND;
 DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID'|| V_EMP_ID);
 DBMS_OUTPUT.PUT_LINE('SALARY'|| V_SALARY);
 DBMS_OUTPUT.PUT_LINE('HIREDATE'|| V_HIRE_DATE);
 END LOOP;
 CLOSE CUR_EMP_IN_DEPT;
END;



DECLARE 
 CURSOR CUR_UPDATE_COMMISSION_PCT
 IS 
 SELECT EMP_ID, SALARY FROM EMP WHERE JOB_ID IN('MK_REP','PR_REP');
     v_emp_id emp.emp_id%TYPE;
     v_sal emp.salary%TYPE;
     v_commission_pct emp.commission_pct%TYPE;
BEGIN
  OPEN CUR_UPDATE_COMMISSION_PCT;
  LOOP
    FETCH CUR_UPDATE_COMMISSION_PCT INTO v_emp_id,v_sal;
    EXIT WHEN CUR_UPDATE_COMMISSION_PCT%NOTFOUND;
    IF v_sal>10000 THEN
        v_commission_pct:=0.1;
    ELSIF v_sal>=7000 AND v_sal<=10000 THEN
        v_commission_pct:=0.15;
    ELSE
      v_commission_pct:=0.2;
    END IF;
    UPDATE EMP SET COMMISSION_PCT = v_commission_pct where emp_id = v_emp_id;
  END LOOP;
  CLOSE CUR_UPDATE_COMMISSION_PCT;
  EXCEPTION
  WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Some error occured');
END;
  