--DROP TABLE POLICY;
--DROP TABLE CUSTOMER;
--DROP TABLE PURCHASE;

CREATE TABLE POLICY (POLICY_ID NUMBER(6), POLICY_NAME VARCHAR2(20), 
TYPE_OF_INSURANCE VARCHAR2(10),YEARS NUMBER(3), RATE_OF_INTEREST FLOAT(5),
INITIAL_AMOUNT FLOAT(20), FINAL_AMOUNT FLOAT(20),
CONSTRAINT PK_POLICY_ID PRIMARY KEY (POLICY_ID));

CREATE TABLE CUSTOMER(CUST_ID VARCHAR2(6),
CUSTOMER_NAME VARCHAR2(20) NOT NULL,
ADDRESS VARCHAR2(50),
EMAIL_ID VARCHAR2(20), 
CONTACT_NO NUMBER(13),
CONSTRAINT PK_CUST_ID PRIMARY KEY (CUST_ID));

CREATE TABLE PURCHASE(PURCHASE_ID VARCHAR2(6) PRIMARY KEY,
POLICY_ID NUMBER(6),
CUST_ID VARCHAR2(6),
CONSTRAINT FK_PolicyPurchase FOREIGN KEY(POLICY_ID) REFERENCES POLICY(POLICY_ID),
CONSTRAINT FK_PolicyCustomer FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID));


--SELECT * FROM user_constraints WHERE TABLE_NAME='PURCHASE';
CREATE TABLE PRODUCTS(PROD_ID VARCHAR2(6),PROD_NAME VARCHAR2(12),PRICE_PER_KG